
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.cmls.ui;

import java.awt.BasicStroke;


import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;

import java.awt.Shape;
import java.awt.Stroke;

import java.awt.image.BufferedImage;
import sm.cml.graficos.Figure;

/**
 *
 * @author carla
 */
public class Lienzo2DImagen extends Lienzo2D {
    private BufferedImage img;
    public boolean isPaint=false;
    public int countdraw=0; 

    /**
     * Creates new form Lienzo2DImagen
     */
    public Lienzo2DImagen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void setImage(BufferedImage img){
        this.img = img;
        if(img!=null) {
            setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
        }
    }
    public BufferedImage getImage(){
        return img;
    }

    public BufferedImage getImage(boolean drawVector) {
        if (drawVector) {
            BufferedImage imgOut =img;
            //new BufferedImage(img.getWidth(),img.getHeight(),img.getType());
            Graphics g= imgOut.createGraphics();
            g.drawImage(imgOut, imgOut.getHeight(),imgOut.getWidth(), this);
            
            for(Figure f: vShape){
                
                this.repaint();
            }
            
            return imgOut;
        } else {
            return getImage();
        }

    }

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        if(img!=null){
            g.drawImage(img,0,0,this);
            Shape clipArea= new Rectangle(0,0,img.getWidth(),img.getHeight());
            float patronDiscontinuidad[] = {5.0f, 5.0f};
            Stroke trazo = new BasicStroke(5.0f,
                    BasicStroke.CAP_ROUND,
                    BasicStroke.JOIN_MITER, 5.0f,
                    patronDiscontinuidad, 0.0f);
            g2d.setStroke(trazo);
            g2d.setClip(clipArea);
            g2d.draw(clipArea);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

//    private Graphics2D draw(Graphics2D g2d) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
